### ISSUE TITLE
Project Funds

### ISSUE THREAD

**Issue by bleeeeee** [sfbrigade/twabler#1]
An application for project funds needs to be made.  The application must include
	- Diagrams of the general pipelene/infrastructure and data flow
	- Estimated cost of the project with breakdowns
	- A description of the Data Science application

Going to need help from our PM frhino.

**Comment by frhino** [comment]
@bleeeeee Can you create new issues for each of the above?

**Comment by bleeeeee** [comment]
Closing and fragmenting into new related issues.

**Comment by bleeeeee** [comment]
See https://github.com/sfbrigade/twabler/issues/4 , https://github.com/sfbrigade/twabler/issues/5 , https://github.com/sfbrigade/twabler/issues/6
